name = "iykyk"
version = "0.3.0"
defaultTargets = ["Iykyk", "IykykExamples", "IykykMetatheory"]
testDriver = "IykykExamples"

[[lean_lib]]
name = "Iykyk"

[[lean_lib]]
name = "IykykExamples"

[[lean_lib]]
name = "IykykMetatheory"
srcDir = "metatheory"
