name = "iykyk"
version = "0.1.0"
defaultTargets = ["Iykyk", "IykykExamples"]
testDriver = "IykykExamples"

[[require]]
name = "aesop"
git = "https://github.com/leanprover-community/aesop"
rev = "v4.33.0"

[[lean_lib]]
name = "Iykyk"

[[lean_lib]]
name = "IykykExamples"
